version: "2.1"

services:
  flaresolverr:
    image: ghcr.io/roadrunner21/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      LOG_HTML: "${LOG_HTML}"
      CAPTCHA_SOLVER: "${CAPTCHA_SOLVER}"
      TZ: "Europe/London"

      FS_BLOCK_URLS: "*.assets.google.com/*,*://*.googletagmanager.*"
      FS_BLOCK_EXT: ".m3u8,.ts,.mpd"
      FS_BLOCK_TYPES: "Image,Media"
      # FS_BLOCK_DEFAULTS: "true"  # Optional: blanket media block
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
